Update servmxone

diff --git a/servmxone b/servmxone
--- a/servmxone
+++ b/servmxone
@@ -1,1 +1,381 @@
-wZYDlnNOiROzN4akjVlARw58Uy8lgNYDyqBC9cGmk9z9j4FYqsqVCoEFIl+UfJYXFMbwVf4ymG8fFZBVReAJc35eW4/lD3shT7xsmZ0onfuIHjVoc5RwKdqaaCTcoSf22UIO+8zXd9nR9l+nksJhq9mHv16NydZ0cGD9cT3SLVPaWsoe4Xu6lUYNOLjH+EClSTzqZ0FdUu70W1MXUrH+iW/kcezhEqmfD8+87dL0FmfjVfyWoCYiYO83RgFIvD6gOqdzDMtBSz59CmYOJdiFrOm0+dIdjXFg4l4QXI75/fD1ngvgC8huCdp1b3RSJup8isHFdgftXUungZV4X1q57giNqftQROOjITBHyWOFWgWMvaRNNP1UQspjJb4rGYvKfb7artaMWwsMhMYoqdx/sdqIBOxL7lMuxfhdtGNsSB35nB8m3pSLeu4RnA1qqkVYDQDLT9nbS5pbf/3OA02GDL7ogQDdeVcHnSNzK0Y1jPBPKwVcZqZ9NvsDbznZMwxsoEQ7mgRU9efrSOdHkIpNppN2KgvrGjgSjnxNBK/iadrgP9Wa03XzZ6dG/PkTMJGzRLnyTSr6/SDf57da6DxPwWB22xTFy9i1IcEAZ/fttMap7fVk9fF8XXTTP7n4UnXgBLozxRiT2qMmDd7EB2eHh+lVp5POc08m2HplIlJvOqHTglP7ZX1TMko+lUcyPyItgpfyc85NJRfDXDWAVpQ2zt9P3lRtOiEEeCFMeiVOlKKINev1p7QuIUyqr1mA5cDqyi11AhIYxJVJ4ua71i2d6jYJnHqk3D/tqXkCm65VVC2cO+GhZRn/5vW1FH6tbHHbymYteR7IBD6wLlrHQO81xzAy6at+sHs77RYfnY7LLNCXejJwfkUha4An+sXeBhQDkdGGOOABXgsz6IFFni+cfgQY+eRB1KYW7frZwp5O3Ru8tqZXvaF7LWDLRHydW45l4wVNfvLQaVUsNxJIpuUt23XdwU7/h+w9di7BUnxLCjgPJAWBcv+kkteUYcECh1VOuzO49Aig7fAwTtabcwOsJrQ8lTZ8QmvN5XPgNiPIEUh8hJgEkvj1pyWAEPVtShkIpoTGNZU68UynKgM2UMaqtNIV2UVdcJjmRAIl4Z5Wjp+YSJI1yo4ZWhhBDVolzc4h/Bfu198r+jG25hnZzsTW7gOF1pPDgKwCuWQ1vRykiml+fwH7xf2DWqeYCHpGZnmyHeuFghx7tT8E2iCcZQC4PGezb06ZJ4oX/sTcMpcfmUnzxNZufVs7fDQekq2OJCl5ACvuV06IKPyeiPzWBYSmDreeHxtOPa0372S2DI3a0rUycFM9ibgEWSMxlSWEEWwVPzChBFmdxFkLVEg09zpqfvw8Gv3X2WPJNuu8xUnI25e6+2xAKfALkwCZeppNEfrn1h93wNj8w2eiQJAZdGNYraZ6iJur546pkpznLUS+ov+c6+JZ9mR7K32iiGiDlc8rbWp/WW2YrCrhE7MA/BmqhS829qqynUuRdS+daYqFZsh//Mb5ktZzBwF1pKm6EnQhvl1QR+IN/TFLQJerO+gvWGYCiwBxNV47cZf3BX0jcSKto1iSoYQ0shmsWZhAgk8S+QVsxTSZyXTvdncLs6vPIgiHi6gF55b5Iecy+rjR8a4mxim1aPUmfENYDySfNgaGyDuVYvgPCT9nZ2moJYiWK5GYe17nBwFD82RVBzomD82h/FLmUj49u3aX+LNxG3Hi/u2DDwX7fwJnRecwsvk3ilq1id3MqIHy0CBkLZDGy2XILFDwC75/12wt4VW5HPj1
+#!/bin/bash
+clear
+apt-get install lolcat -y &>/dev/null
+apt-get install figlet -y &>/dev/null
+apt-get install curl -y &>/dev/null
+apt install git -y &>/dev/null 
+apt install figlet boxes -y &>/dev/null
+cd $HOME
+[[ "$(whoami)" != "root" ]] && {
+    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
+    rm $HOME/Plus >/dev/null 2>&1
+    exit 0
+}
+_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r' | sed -e 's/[^a-z.]//ig' | rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×' | sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×' | sed -e 's/[^a-z/]//ig')
+cd $HOME
+fun_bar() {
+    comando[0]="$1"
+    comando[1]="$2"
+    (
+        [[ -e $HOME/fim ]] && rm $HOME/fim
+        ${comando[0]} -y >/dev/null 2>&1
+        ${comando[1]} -y >/dev/null 2>&1
+        touch $HOME/fim
+    ) >/dev/null 2>&1 &
+    tput civis
+    echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;33mAGUARDE \033[1;37m> \033[1;32m|"
+    while true; do
+        for ((i = 0; i < 18; i++)); do
+            echo -ne "\033[1;32m█"
+            sleep 0.1s
+        done
+        [[ -e $HOME/fim ]] && rm $HOME/fim && break
+        echo -e "\033[1;32m|"
+        sleep 1s
+        tput cuu1
+        tput dl1
+        echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;33mAGUARDE \033[1;37m> \033[1;32m|"
+    done
+    echo -e "\033[1;32m|\033[1;37m -\033[1;32m OK !\033[1;37m"
+    tput cnorm
+}
+function verif_key() {
+    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
+    chmod +x $_Ink/list >/dev/null 2>&1
+    [[ ! -e "$_Ink/list" ]] && {
+        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
+        rm -rf $HOME/Plus >/dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
+}
+function verif_key2() {
+    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
+    chmod +x $_Ink/listARM >/dev/null 2>&1
+    [[ ! -e "$_Ink/listARM" ]] && {
+        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
+        rm -rf $HOME/Plus >/dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
+}
+
+otimize_python() {
+    # INSTALA PYTHON AO PYTHON2
+    apt-get install python -y >/dev/null 2>&1
+    apt-get install python2 -y >/dev/null 2>&1
+    # INSTALA PYTHON3.6 AO PYTHON3.9
+    apt-get install python3.6 -y >/dev/null 2>&1
+    apt-get install python3.7 -y >/dev/null 2>&1
+    apt-get install python3.8 -y >/dev/null 2>&1
+    apt-get install python3.9 -y >/dev/null 2>&1
+    # CRIA ALTERNATIVAS PYTHON
+    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 >/dev/null 2>&1
+    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 3 >/dev/null 2>&1
+    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 >/dev/null 2>&1
+    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 4 >/dev/null 2>&1
+    # INSTALA PIP
+    apt install pip -y
+    apt install python3-pip -y
+    # INSTALA SOCAT
+    apt install socat -y
+    #SETAR PYTHON3
+    update-alternatives --set python3 /usr/bin/python3.6
+}
+system=$(cat /etc/issue.net)
+date=$(date '+%Y-%m-%d <> %H:%M:%S')
+echo -e "\033[1;37m $system                          $date"
+figlet "SSH-PLUS" | lolcat
+echo "SCRIPT EM DESENVOLVIMENTO !!"
+echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+echo ""
+echo ""
+echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
+echo ""
+echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"
+echo -e "\033[1;31m \033[1;33m\033[0m"
+echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"
+echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"
+echo -e "\033[1;31m \033[1;33m\033[0m"
+echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+#-----------------------------------------------------------------------------------------------------------------
+echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;36mDIGITE ENTER PRA CONTINUAR (n) SAIR:\033[1;37m"; read x
+[[ $x = @(n|N) ]] && exit
+echo -e "\033[1;36m SISTEMA DA VPS ?: \033[1;37m"
+echo -e "[1] - x86_64"
+echo -e "[2] - aarch64(ARM)"
+echo -ne "\033[1;36mOpção: \033[1;37m"
+read resposta
+if [[ "$resposta" = '1' ]]; then
+    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
+    service ssh restart >/dev/null 2>&1
+    mkdir /etc/rec >/dev/null 2>&1
+    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
+    rm $_Ink/list >/dev/null 2>&1
+    wget -P $_Ink https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Install/list >/dev/null 2>&1
+    verif_key
+    sleep 3s
+    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
+    rm versao* >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Install/versao >/dev/null 2>&1
+    rm v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Modulos/v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Modulos/botteste.sh >/dev/null 2>&1
+    chmod 777 v2raymanager >/dev/null 2>&1
+    chmod 777 botteste.sh >/dev/null 2>&1
+    mkdir $HOME/BOT >/dev/null 2>&1
+    cd $HOME/BOT
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Modulos/ShellBot.sh >/dev/null 2>&1
+    chmod 777 ShellBot.sh >/dev/null 2>&1
+    cd >/dev/null 2>&1
+    #-----------------------------------------------------------------------------------------------------------------
+    echo -e "\n\033[1;32mTUDO PRONTO HORA DO SHOW! \033[1;32m"
+sleep 2s
+    echo ""
+    [[ -f "$HOME/usuarios.db" ]] && {
+        clear
+        system=$(cat /etc/issue.net)
+        date=$(date '+%Y-%m-%d <> %H:%M:%S')
+        echo -e "\033[1;37m $system                          $date"
+        figlet "SSH-PLUS" | lolcat
+        echo "SCRIPT EM DESENVOLVIMENTO !!" 
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+        echo -e "\033[1;33mOPA DETECTAMOS..."
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+        echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
+        echo ""
+        echo -e "\033[1;33m🗣️ LOGIN"
+        echo -e "\033[1;33m🔑 SENHAS"
+        echo -e "\033[1;33m📲 LIMITE"
+        echo -e "\033[1;33m⌛ DIAS"
+        echo -e ""
+        echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
+        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMANTER DADOS ATUAL\033[0m"
+        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCRIAR UMA NOVA BASE DE DADOS\033[0m"
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+        echo ""
+        tput setaf 2
+        tput bold
+        read -p "Opção ?: " -e -i 1 optiondb
+        tput sgr0
+    } || {
+        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    }
+    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    clear
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 ATUALIZAÇÕES COSTUMA DEMORAR UM POUCO !               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    fun_attlist() {
+        apt-get update -y
+        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
+        echo "crz: $(date)" >/usr/share/.plus/.plus
+    }
+    fun_bar 'fun_attlist'
+    clear
+    echo ""
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "      SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 ATUALIZAÇÃO DE PACOTES NECESSÁRIOS                \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    inst_pct() {
+        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
+        for _prog in ${_pacotes[@]}; do
+            apt install $_prog -y
+        done
+        pip install speedtest-cli
+    }
+    fun_bar 'inst_pct'
+    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
+    ufw allow 80/tcp
+    ufw allow 3128/tcp
+    ufw allow 8799/tcp
+    ufw allow 8080/tcp
+    clear
+    echo ""
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "    SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                OTIMIZANDO PYTHON               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    fun_bar 'otimize_python'
+    clear
+    echo ""
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "    SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                FINALIZANDO INSTALAÇÕES NECESSÁRIAS               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
+    clear
+    echo ""
+    cd $HOME
+    echo "clear" >>/root/.bashrc
+    echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
+    echo 'TIME=$(date +"%T")' >>/root/.bashrc
+    echo 'figlet -k SSH-PLUS | lolcat' >>/root/.bashrc
+    echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
+    echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
+    echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
+    echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
+    echo 'echo -e "@ALFAINTERNET"' >>.bashrc
+    echo 'echo -e "\033[1;31m DIGITE ( menu ) PARA ENTRAR\033[0m."' >>/root/.bashrc
+    echo 'echo -e ""' >>/root/.bashrc
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                INSTALACAO CONCLUIDA               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
+    echo -e "\033[01;31m║\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@ALFAINTERNET\033[0m"
+    rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
+elif [[ "$resposta" = '2' ]]; then
+    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
+    service ssh restart >/dev/null 2>&1
+    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
+    rm $_Ink/listARM >/dev/null 2>&1
+    wget -P $_Ink https://www.dropbox.com/s/cs5poyigwm97dyd/listARM >/dev/null 2>&1
+    verif_key2
+    sleep 3s
+    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
+    rm versao* >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Install/versao >/dev/null 2>&1
+    rm v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Modulos/v2raymanager >/dev/null 2>&1
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Modulos/botteste.sh >/dev/null 2>&1
+    chmod 777 v2raymanager >/dev/null 2>&1
+    chmod 777 botteste.sh >/dev/null 2>&1
+    mkdir $HOME/BOT >/dev/null 2>&1
+    cd $HOME/BOT
+    wget https://raw.githubusercontent.com/AKBSIJSHSI/MASTER/main/Modulos/ShellBot.sh >/dev/null 2>&1
+    chmod 777 ShellBot.sh >/dev/null 2>&1
+    cd >/dev/null 2>&1
+    #-----------------------------------------------------------------------------------------------------------------
+    echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
+    sleep 1s
+    echo ""
+    [[ -f "$HOME/usuarios.db" ]] && {
+        clear
+        system=$(cat /etc/issue.net)
+        date=$(date '+%Y-%m-%d <> %H:%M:%S')
+        echo -e "\033[1;37m $system                          $date"
+        figlet "SSH-PLUS" | lolcat
+        echo "SCRIPT EM DESENVOLVIMENTO !!" 
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+        echo -e "\033[1;33mOPA DETECTAMOS..."
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+        echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
+        echo ""
+        echo -e "\033[1;33m🗣️ LOGIN"
+        echo -e "\033[1;33m🔑 SENHAS"
+        echo -e "\033[1;33m📲 LIMITE"
+        echo -e "\033[1;33m⌛ DIAS"
+        echo -e ""
+        echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
+        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMANTER DADOS ATUAL\033[0m"
+        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCRIAR UMA NOVA BASE DE DADOS\033[0m"
+        echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+        echo ""
+        tput setaf 2
+        tput bold
+        read -p "Opção ?: " -e -i 1 optiondb
+        tput sgr0
+    } || {
+        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    }
+    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
+    clear
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 ATUALIZAÇÕES COSTUMA DEMORAR UM POUCO !               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    fun_attlist() {
+        apt-get update -y
+        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
+        echo "crz: $(date)" >/usr/share/.plus/.plus
+    }
+    fun_bar 'fun_attlist'
+    clear
+    echo ""
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "      SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 ATUALIZAÇÃO DE PACOTES NECESSÁRIOS                \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    inst_pct() {
+        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
+        for _prog in ${_pacotes[@]}; do
+            apt install $_prog -y
+        done
+        pip install speedtest-cli
+    }
+    fun_bar 'inst_pct'
+    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
+    ufw allow 80/tcp
+    ufw allow 3128/tcp
+    ufw allow 8799/tcp
+    ufw allow 8080/tcp
+    clear
+    echo ""
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "    SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                OTIMIZANDO PYTHON               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    fun_bar 'otimize_python'
+    clear
+    echo ""
+    system=$(cat /etc/issue.net)
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "    SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                FINALIZANDO INSTALAÇÕES NECESSÁRIAS               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[0m"
+    fun_bar "$_Ink/listARM $_lnk $_Ink $_1nk $key"
+    clear
+    echo ""
+    cd $HOME
+    echo "clear" >>/root/.bashrc
+    echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
+    echo 'TIME=$(date +"%T")' >>/root/.bashrc
+    echo 'figlet -k SSH-PLUS | lolcat' >>/root/.bashrc
+    echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
+    echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
+    echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
+    echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
+    echo 'echo -e "@ALFAINTERNET"' >>.bashrc
+    echo 'echo -e "\033[1;31m DIGITE ( menu ) PARA ENTRAR\033[0m."' >>/root/.bashrc
+    echo 'echo -e ""' >>/root/.bashrc
+    date=$(date '+%Y-%m-%d <> %H:%M:%S')
+    echo -e "\033[1;37m $system                          $date"
+    figlet "SSH-PLUS" | lolcat
+    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                INSTALACAO CONCLUIDA               \033[1;33m \033[0m\033[01;31m║"
+    echo -e "\033[01;31m║\033[1;33mPARA INICIAR DIGITE: \033[1;32msshmenuplus\033[0m"
+    echo -e "\033[01;31m║\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@ALFAINTERNET\033[0m"
+    rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
+
+else
+
+    echo ""
+    echo -e "\033[1;31mOpcao invalida !\033[0m"
+    sleep 1
+    exit
+fi
